### ISSUE TITLE
Fully Connected Layers not Supported

### ISSUE THREAD

**Issue by bonfab** [evandez/neuron-descriptions#17]
It seems like fully connected layers are not supported.

I tried to run Milan on the "fc" layer of resnet18 and received following error:

```
Traceback (most recent call last):                                                                                   
  File "neuron-descriptions/scripts/compute_exemplars.py", line 113, in <module>
    compute.discriminative(model,
  File "/workdir/neuron-descriptions/src/exemplars/compute.py", line 336, in discriminative
    return compute(compute_topk_and_quantile,
  File "/workdir/neuron-descriptions/src/exemplars/compute.py", line 182, in compute
    topk, rq = tally.tally_topk_and_quantile(_compute_topk_and_quantile,
  File "/workdir/neuron-descriptions/src/deps/netdissect/tally.py", line 216, in tally_topk_and_quantile
    sample_tk, sample_q = call_compute(compute, batch)
  File "/workdir/neuron-descriptions/src/deps/netdissect/tally.py", line 670, in call_compute
    return compute(*batch)
  File "/workdir/neuron-descriptions/src/exemplars/compute.py", line 324, in compute_topk_and_quantile
    activations = hiddens.permute(0, 2, 3, 1).reshape(-1, channels)
RuntimeError: number of dims don't match in permute
```

It seems like the permute operation expects four dimensions.

**Comment by bonfab** [comment]
One can add a hiddens transform similar to vit
```
def spatialize_fc(hiddens):
    return hiddens[:,:,None,None]
```

**Comment by evandez** [comment]
Yup, that's correct. You should be able to specify these transforms in the exemplars config:
https://github.com/evandez/neuron-descriptions/blob/main/src/exemplars/models.py#L111
